### ISSUE TITLE
Operate simultaneously as a matrix bot and external API

### ISSUE THREAD

**Issue by rzadp** [paritytech/polkadot-testnet-faucet#205]
Currently, a single deployment of the faucet backend operates in one of two modes:

| Mode | Description |
|---|---|
| `EXTERNAL_ACCESS: false` (default) | The backend expects requests to be coming from the (trusted) matrix bot. We trust matrix account registration to be the first line defense against spam. |
| `EXTERNAL_ACCESS: true` | The backend expects requests to be coming from external (untrusted) API calls. We add captcha as a first line defense against spam |

I'm opening this issue to discuss the matter of changing the backend so that it could operate in both modes simultaneously.

### Why it could be beneficial

1. Decrease the amount on deployments

It is probably safer to run the two different modes in separate deployments, in order to separate the risk of draining the faucet.
But if we want to add the API mode to every environment, that we would **double the amount of deployments**.
If we tolerate the risks (e.g. staging?), or add two separate treasuries in code, we could reduce the amount of new deployments needed.

2. Simplify testing

It would be easier to test a single instance in different ways, than to test two different instances.
Can relate to E2E tests, local development, manually testing staging.

3. We're not losing anything.

We would not lose the possibility to operate in these two modes separately.
No matter the code changes, you can always deploy the backend without exposing any external ports (so matrix bot only), or deploy the backend container without the bot container (so external API only).

### Possible ways

1. Detect where the request is coming from

If we can detect automatically whether the request is coming from the sibling docker container or not, we can use it to deduct whether the request is coming from the bot or not.

(I spent some time to explore this direction. As you dig into it, there are more and more caveats and now I think this is NOT the right way).

2. Add a secret password/token

We could add a secret password/token shared between the backend and the bot.
Then, if an API requests has that password, the backend knows it's coming from the bot.

Seems simple to implement but would add operation complexity to manage the secret.

3. Leave it as it is

Also an option - we could not make any changes and leave it as it is if we're happy with current approach.

**Comment by rzadp** [comment]
@paritytech/opstooling does anyone has any thoughts on this?

**Comment by Bullrich** [comment]
I like option 2 as it requires the less involment from a devops side.

Can we have the secret being set in an env variable on build and then simply set that same secret on the bot?

**Comment by rzadp** [comment]
> Can we have the secret being set in an env variable on build and then simply set that same secret on the bot?

I think so, that would be nice because it wouldn't need a runtime variable.

**Comment by Bullrich** [comment]
> > Can we have the secret being set in an env variable on build and then simply set that same secret on the bot?
> 
> I think so, that would be nice because it wouldn't need a runtime variable.

Yeah, I would say this could be the easiest way of handling secrets without increasing the complexity too much as it would be used for only one case.

Let's see what the rest of @paritytech/opstooling thinks

**Comment by mordamax** [comment]
> checking if it's a sibling docker container

this is mixing a business logic with a deployment environment (or not mixing, but we're making it dependent on env, which is temporary) ? doesn't look like a good practice imo 🤔


Thinking outloud...
if this is one server, which accepts "external" (web) and "internal" (matrix)...
lets say we have an api
`single-server.com/drip`
in one case (external==true) it accepts the username + address, otherwise (external==false) address+captcha token
but still we will need 2 different wallets for this right? as web version is managed by INK, while matrix - devops

so then the env would look like:
Server 1:
WEB_MNEMONIC=... (westend)
BOT_MNEMONIC=... (westend)

Server 2
WEB_MNEMONIC=... (rococo)
BOT_MNEMONIC=... (rococo),

etc...
but if we expose the /drip endpoint for bot, then anyone can POST a query there with "fake_username123" + "address" and if you generate tons of addresses, you can drain it pretty quickly.. so there should be some additional "auth" from the bot to server then, to make sure that it comes from the bot, and not from someone else. Looking up to whether it comes from the sibling docker container would not be a stable solution for this IMO.

not making a final conclusion yet, prob still worth discussing other ways of how can we simplify it?

one of the options I had in mind - if we have a one server, may be making a mapping of configs for all kind of networks

so it may support /drip?network=rococo&parachain_id=&token=123xyz, taking all needed configs of env.server.config.json from some map.. so there will be 2 servers, 1st for bot with map, and 2nd for server with map of networks. But still not sure about it

**Comment by rzadp** [comment]
I made changes in https://github.com/paritytech/substrate-matrix-faucet/pull/219 to make the bot backend and endpoint backend run on two different ports.

It's currently implemented and all the tests pass.
But it cannot be merged, not without coordinating the change of environment variables.

@paritytech/opstooling Can you please take a look at that PR and review it?

**Comment by mordamax** [comment]
@rzadp the env variable solution, where depends on server it would set either WEB or BOT mnemonic looks a bit ambiguous & harder to infer. if we indeed want to reduce deployments (i am still not sure why), i'd go with a config maps, so each network + web/bot mode would be configured fully & separately, instead of playing with env variables. But this also adds a complexity on maintaining this map config, as it should be stored in secret vault as a string, so there's increased level of a mistake of parsing json and support overall

 if we really want to go this way, may be would be better to spit it a bit differently.. like for BOT - do we really need/want bot to call the rest API? (i mean like /api/bot) Can't BOT instance which is listening for events from matrix do the drip functionality within an event?

and then if we have a web api, that's a separate application, with its own config, like we have, and then it's only for external use..

but we have a one codebase, for both, then the drip core functoinality - couldit  be moved out into a lib? and be reused within bot and web api?

then the tests could be simplified and we could reduce deployments etc
