### ISSUE TITLE
Create chain selection page

### ISSUE THREAD

**Issue by Bullrich** [paritytech/polkadot-testnet-faucet#329]
Base on a [discussion](https://github.com/paritytech/polkadot-testnet-faucet/pull/326#discussion_r1270798579_) between @mordamax and @mutantcornholio we should develop a "hub", or a landing page where all the available chains are shown, and the user picks the one he wants.

**Comment by helloitsbirdo** [comment]
The chain selection below could be moved in-line into the form.
![image](https://github.com/paritytech/polkadot-testnet-faucet/assets/93915849/7d886b09-21c1-4f5b-93f2-a4fba9837c58)

The order can be:
`Chain` (Rococo, Westend, etc)
`Network` (Bridge Hub, Asset hub, etc)
`Address`

cc: @Bullrich

**Comment by mordamax** [comment]
I'd probably think of it as parity supported test chains, since we manage seeds/balances. 
While the other testnet owners, which are not managed by our team, could just fork this repo and deploy it on their own environment, providing necessary chains and looking after its balances. 

or may be i don't fully understand how exactly other testnets will be added, and who will control the balances etc

**Comment by helloitsbirdo** [comment]
As an alternative, the faucet could still list other networks and then just redirect the page if the user selects that Chain.

e.g. In the `Chain` dropdown, `Frequency` is an option
Upon selecting `Frequency`, the page redirects to faucet.rococo.frequency.xyz

At least it surfaces the other faucets and makes them discoverable
